// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0Vw_BpfAeygog3lDPa8wUFqaIb1w8-XQ',
    appId: '1:948806328640:web:29c0bce9fe67c807f61aa5',
    messagingSenderId: '948806328640',
    projectId: 'flutter-db-1320c',
    authDomain: 'flutter-db-1320c.firebaseapp.com',
    storageBucket: 'flutter-db-1320c.appspot.com',
    measurementId: 'G-327CDBB3HF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKjaxW3kAB6hhRjl16iWCKuxZNwpZH_p8',
    appId: '1:948806328640:android:186d31289a09e9e8f61aa5',
    messagingSenderId: '948806328640',
    projectId: 'flutter-db-1320c',
    storageBucket: 'flutter-db-1320c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp-41FRB3n0HY23biZ1kEgGxK7XrMEew4',
    appId: '1:948806328640:ios:ffe9e758617cce19f61aa5',
    messagingSenderId: '948806328640',
    projectId: 'flutter-db-1320c',
    storageBucket: 'flutter-db-1320c.appspot.com',
    iosBundleId: 'com.example.p8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp-41FRB3n0HY23biZ1kEgGxK7XrMEew4',
    appId: '1:948806328640:ios:ffe9e758617cce19f61aa5',
    messagingSenderId: '948806328640',
    projectId: 'flutter-db-1320c',
    storageBucket: 'flutter-db-1320c.appspot.com',
    iosBundleId: 'com.example.p8',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0Vw_BpfAeygog3lDPa8wUFqaIb1w8-XQ',
    appId: '1:948806328640:web:3ec0505e3dc66162f61aa5',
    messagingSenderId: '948806328640',
    projectId: 'flutter-db-1320c',
    authDomain: 'flutter-db-1320c.firebaseapp.com',
    storageBucket: 'flutter-db-1320c.appspot.com',
    measurementId: 'G-VCP5ER5C7G',
  );
}
